markdown: rdiscount
permalink: /:title/
url: http://89ao.info
name: 89Ao.info
author: AoGang
qq: 103230005
email: 89ao@live.com
duoshuo: 89ao
#beian: 浙ICP备12026616号
#cnzz: 119959
weibo: 2067815867
github: 89ao
pygments: true
safe: true
paginate: 20
about: 在读研究生，准备跨行做码农。
